FROM tomcat:9-jdk11-temurin

COPY webapp.war /usr/local/tomcat/webapps/webapp.war

EXPOSE 8080

CMD ["/usr/local/tomcat/bin/catalina.sh", "start"]

#catalina.sh start  INSIDE DOCKER
#docker build -t tomcat:v5 .
#docker run -it -p 9999:8080 tomcat:v5 bash
